const PodcastPara = [
    {
        heading1:"The Arcgate Podcast: Retail Technology has Changed the Experience of Shopping Enormously",
        paragraph1: "Continued growth in e-commerce space, improvements in mobile technology and increasing social media use has not only made retailers re-evaluate the traditional practices, but more importantly, it has forever changed consumers shopping habits. Recognizing the demand for new retail technology solutions, digital savvy retailers are combining traditional practices with new technology helping them serve their customers better.",
        paragraph2: "Would love for you to hear this podcast and tell us what you think. We can be reached on twitter @arcgateinc",


        heading2:"The Arcgate Podcast: Meet the team – Episode 2",
        paragraph3: "As we start to hire more and more people, at times, we miss out on getting to know all our employees – and so we constantly make efforts to maintain a tight-knit culture. That’s why it’s crucial for us to find new ways to get to know our expanding workforce by cultivating a close-knit culture through every stage. So here in a series of podcasts, you will get to know a little more about what drives our people to achieve, accomplish and accelerate!",
        paragraph4: "#Arcgatian Anshul – He quit an exciting sea life to settle ashore! A passionate engineer and a data lover, we are glad he found his calling here at Arcgate and was able to move back to Udaipur with his family. After all, it all boils down to what one really wants from one’s life and how far one can go to achieve one’s dreams.",


        heading3: "The Arcgate Podcast: Meet the team – Episode 1",
        paragraph5: "Our employees strive every day to make a difference and we see for real that our strong relationships do make an important difference. So we want to introduce you to some of our employees. In a series of podcasts, you will get to know a little more about what drives our people to achieve, accomplish and accelerate!",
        paragraph6: "#Arcgatian Prashant: We admire his coolness very much which is the basic and guiding factor for all his virtues and fine qualities. Having the ability to remain calm is a powerful tool he has, which inspires people to trust him more while at the same time improving his ability to make better decisions and think more clearly under pressure.",


        heading4: "The Arcgate Podcast: Meat Alternatives, Personalized Nutrition and AI for Food Delivery",
        paragraph7: "With many investors and big players of the food industry backing the trend of alternative meat or cultured meat also known as lab-grown meat, it may only be a matter of time before customer perception will adjust. And driven by an massive increase in online grocery and food deliveries leading startups and companies in this space are embracing artificial intelligence (AI) in a big way to better serve a fast-changing customer behavior and reduce errors in order to enhance customer experiences.",


        heading5: "The Arcgate Podcast: Receipt Data is a Holy Grail For Marketers",
        paragraph10: "Loyalty programs are imperative for brands and marketers and are a surefire way to increase growth, help retain customers and establish a brand’s reputation. In order to ensure and launch an effective loyalty program brands have to take advantage of technological advances like the OCR (optical character recognition) and image scanning to collect receipt data and turn it into data gold mines.",

        heading6: "The Arcgate Podcast: Real Estate Tech – A Promising Space for Investors and Venture Capitalists in 2018",
        paragraph11: "Real estate tech startups have seen a steady rise over the last five years and is said to be one of the most promising industry for investors and venture capitalists. New age technology startups are innovating and relentlessly working to full the technology gap to drive efficiency and effectiveness to reshape the traditional real estate industry.",

        heading7: "The Arcgate Podcast: Real Estate Tech is Building the Industry’s Future",
        paragraph12: "As the real industry grows increasingly aware of the cost and time-saving benefits of technology spurring adoption and boosting sales, investor interest continues to skyrocket. Though property listings and property management handled online has become the new normal in the industry; emerging tech platforms are looking to change the transaction-oriented aspects of the business which are still overwhelmingly handled in person. From home listing apps and websites to virtual reality helpers hitting the market, technology is indeed transforming the traditional process of buying and selling homes. Tech startups in this space are geared towards changing everything from real estate advertising, peer-to-peer leasing, finding shared living, increasing both the quality and quantity of tech solutions.",

        heading8: "The Arcgate Podcast: Learning Algorithms Need Data to Train On",
        paragraph13: "AI is fascinating and life-changing on its own. And big data, too, has incredible potential power on-its-own. But together, these are poised to change many industries and businesses forever. As the barrier to implementing these technologies disappear, more and more industries will put AI technologies into use; and more and more AI startups will emerge with new ideas and a lot of funding. However, big data is essential to AI’s success. AI itself doesn’t reason and deduce the way human minds do. Instead it learns through trial and error. That’s why having large amounts of data is more important than ever; and the more accurate data AI is trained on, the more accurate it will become.",

        heading9: "The Arcgate Podcast: Sharing economy is going sharing-crazy with everything from bikes and spaces",
        paragraph14: "Sharing is caring – or is it? Airbnb and Uber have engaged private house and cars in collaborative consumption and made it available to many. Technology has redefined the concept of sharing and renting. A sizeable sharing economy is opening up on apps and mobile allowing users to pick and share a mind boggling array of stuff. We look at some stories from around the web on what’s happing in the sharing economy space as almost everyone’s onto sharing these days – and from bikes to sugar – there seems to a huge array of shareable good services out there. Hear it from us on few such startups taking advantage of the rise of sharing economy.",

        heading10: "The Arcgate Podcast: From borrowing things to renting homes, the sharing-economy is showing no signs of slowing down – and it is being driven by technology",
        paragraph15: "The sharing economy has been disrupting and transforming industries, with companies like uber disrupting the taxi industry and Airbnb disrupting the hospitality industry. The sharing economy has shown tremendous value in delivering incremental revenues for asset owners and improving the options for customers. In fact this collaborative creation, distribution and consumption of peer-to-peer resources have become a defining part of the consumer markets. Sharing economy actually has a shot at disrupting any industry in which products can be shared for use. If we think about it the industries already disrupted by sharing economy can said to be equipment rentals, hostels and bed and breakfast, book rentals, car rentals, dvd rentals etc. And those are just a few, there are probably hundreds of industries, both big and small, that the sharing economy could into to disrupt and probably will.",

        heading11: "The Arcgate Podcast: Hot Trends that Will Keep Pushing Advertisers and Publishers to Reinvent Themselves",
        paragraph16: "As more and more advertising technology companies are jumping on the bandwagon of all things programmatic; programmatic methods such as real-time bidding are becoming immensely popular. It is well-known fact in the adtech space that if the rate of supply growth is higher than the rate of demand growth, then the ad prices go down and display inventory becomes a commodity. Thus, by attaching data to inventory – publishers and other players can deliver better content in their ads, helping advertisers reach their customers more precisely, and customers themselves enjoy a user experience tailored to them. However, truly meaningful data in not valuable in quantity alone; it should be enriched, analyzed and combined with other sources such as location, behavioral and senor-related data. The virtual reality and augmented reality will also make it possible to get the most out of mobile advertising – as it is location based, active, interactive and social in one. Whether it’s desktop, tablets or mobile, consumer ad blindness is becoming an ever greater challenge and thus native ads have now firmly established themselves as an alternative and will continue their triumph with new formats.",

        heading12: "The Arcgate Podcast: Food Delivery Companies Need to Adapt Technology to move forward or Leave Money on The Table",
        paragraph17: "Consumers are being given more and more choice when it comes to ordering food online. In fact, technology will continue to be the drive of change in the food delivery space, Online ordering, mobile platforms and self –service take out kiosks are making it super easy for customers to order takeout and delivery more often. The competition to get a fair share of this market will drive companies and brands to find new niches within the industry to stay ahead in the game. Also, restaurants will put up a great fight by developing their own in-house delivery than relying on their party delivery businesses. Data-driven strategies to focus on user experience and harnessing the business will be an important key is gaining traction. Delivery droids, self-driven cars and other artificial intelligence solutions will be tested and rolled out to act as game-changers for this industry.",

        heading13: "The Arcgate Podcast: A list of Techstars Austin Alumni which are Significantly Successful",
        paragraph18: "As one of the most active startups communities in the entire US, Austin has entrepreneurs coming to the city every day to try and make their entrepreneurial dreams come true. And Techstars’ Austin program, which is part of the Techstars’ global ecosystem and aims to empower entrepreneurs to bring new technologies to market, produced these significantly successful startups.",

        heading14: "The Arcgate Podcast: Food Industry Needs to Adapt Big Data Analytics and Technology effectively to stay competitive",
        paragraph19: "Every restaurant, supermarket, convenience store, food truck, cafeteria, manufacturer, distributor – every food business – generates a huge amount of data. The data generated is in form of customers’ orders, delivery locations, social media engagements, loyalty card usage, product inventory, average wait times, experience with delivery, taste of the food, menu availability etc. And as the on-demand marketplace grows, along with advancements in technology, the food industry will have to adapt big data analytics and technology effectively in order to stay competitive, enhance their market reach, increase customer satisfaction and provide better services.",

        heading15: "The Arcgate Podcast: The Shiny New Trends in Real Estate Industry: Technology and Big Data",
        paragraph20: "Real estate is not behind in adapting to modern technology. But there were times when the tools to properly analyze and draw relevant conclusions from data were reserved for bigger real estate companies and investments firms. However, thanks to the boom in personal computing (mobile, tablets, wearables etc.) anybody can find information on a property within a few minutes. Not only that, today mining listing of homes for sale and rent, geographic information systems data, results of consumer surveys, census information etc. and then further analyzing this enormous swathes of information – much of it aggregated from disparate places and formats can reveal actionable trends, patterns and associations when analyzed computationally. It’s time for real estate agents to start applying the insights big data provides to enhance business, attract more buyers and sellers and generate more leads.",   
       
    }
]
export default PodcastPara;